language: php

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL RECIPE_VERSION=1.0.x-dev
    - php: 7.0
      env: DB=MYSQL RECIPE_VERSION=1.1.x-dev
    - php: 7.1
      env: DB=MYSQL RECIPE_VERSION=4.2.x-dev
    - php: 7.2
      env: DB=MYSQL RECIPE_VERSION=4.3.x-dev
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.4.x-dev
    - php: 7.3
      env: DB=MYSQL RECIPE_VERSION=4.x-dev

before_install:
  - composer self-update
  - composer require silverstripe/recipe-cms $RECIPE_VERSION

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
  - cd ~/build/$TRAVIS_REPO_SLUG
  - bash <(curl -s https://codecov.io/bash)
